package hypersquare.hypersquare.util.color;

import net.kyori.adventure.text.format.TextColor;
import oshi.util.tuples.Pair;

import java.util.List;

@SuppressWarnings("unused")
public class Colors {
    public static final TextColor RED_DARK_2 = TextColor.color(0x550000);
    public static final TextColor RED_DARK = TextColor.color(0xAA0000);
    public static final TextColor RED = TextColor.color(0xFF0000);
    public static final TextColor RED_LIGHT = TextColor.color(0xFF5555);
    public static final TextColor RED_LIGHT_2 = TextColor.color(0xFFAAAA);
    public static final TextColor RED_LIGHT_3 = TextColor.color(0xFFD4D4);
    public static final TextColor ORANGE_DARK = TextColor.color(0xD42A00);
    public static final TextColor ORANGE = TextColor.color(0xFF5500);
    public static final TextColor ORANGE_LIGHT = TextColor.color(0xFF7F55);
    public static final TextColor ORANGE_LIGHT_2 = TextColor.color(0xFFAA7F);
    public static final TextColor GOLD_DARK_2 = TextColor.color(0x7F2A00);
    public static final TextColor GOLD_DARK = TextColor.color(0xAA5500);
    public static final TextColor GOLD = TextColor.color(0xFFAA00);
    public static final TextColor GOLD_LIGHT = TextColor.color(0xFFD47F);
    public static final TextColor MUSTARD_DARK_2 = TextColor.color(0xAA7F00);
    public static final TextColor MUSTARD_DARK = TextColor.color(0xD4AA2A);
    public static final TextColor MUSTARD = TextColor.color(0xFFD42A);
    public static final TextColor YELLOW_DARK_3 = TextColor.color(0x7F7F2A);
    public static final TextColor YELLOW_DARK_2 = TextColor.color(0xAAAA55);
    public static final TextColor YELLOW_DARK = TextColor.color(0xD4D455);
    public static final TextColor YELLOW = TextColor.color(0xFFFF55);
    public static final TextColor YELLOW_LIGHT = TextColor.color(0xFFFFAA);
    public static final TextColor YELLOW_LIGHT_2 = TextColor.color(0xFFFFD4);
    public static final TextColor LIME_DARK_2 = TextColor.color(0x55AA00);
    public static final TextColor LIME_DARK = TextColor.color(0x7FD42A);
    public static final TextColor LIME = TextColor.color(0xAAFF55);
    public static final TextColor GREEN_DARK_4 = TextColor.color(0x005500);
    public static final TextColor GREEN_DARK_3 = TextColor.color(0x2A7F00);
    public static final TextColor GREEN_DARK_2 = TextColor.color(0x00AA00);
    public static final TextColor GREEN_DARK = TextColor.color(0x2AD42A);
    public static final TextColor GREEN = TextColor.color(0x55FF55);
    public static final TextColor GREEN_LIGHT = TextColor.color(0x7FFF7F);
    public static final TextColor GREEN_LIGHT_2 = TextColor.color(0xAAFFAA);
    public static final TextColor GREEN_LIGHT_3 = TextColor.color(0xD4FFD4);
    public static final TextColor TEAL_DARK = TextColor.color(0x00D4AA);
    public static final TextColor TEAL = TextColor.color(0x2AFFAA);
    public static final TextColor TEAL_LIGHT = TextColor.color(0x7FFFD4);
    public static final TextColor AQUA_DARK_3 = TextColor.color(0x005555);
    public static final TextColor AQUA_DARK_2 = TextColor.color(0x007F7F);
    public static final TextColor AQUA_DARK = TextColor.color(0x00AAAA);
    public static final TextColor AQUA = TextColor.color(0x2AD4D4);
    public static final TextColor AQUA_LIGHT = TextColor.color(0x55FFFF);
    public static final TextColor AQUA_LIGHT_2 = TextColor.color(0xAAFFFF);
    public static final TextColor AQUA_LIGHT_3 = TextColor.color(0xD4FFFF);
    public static final TextColor SKY_DARK = TextColor.color(0x2A70D4);
    public static final TextColor SKY = TextColor.color(0x55AAFF);
    public static final TextColor SKY_LIGHT = TextColor.color(0xAAD4FF);
    public static final TextColor BLUE_DARK_3 = TextColor.color(0x000055);
    public static final TextColor BLUE_DARK_2 = TextColor.color(0x0000AA);
    public static final TextColor BLUE_DARK = TextColor.color(0x5500FF);
    public static final TextColor BLUE = TextColor.color(0x5555FF);
    public static final TextColor BLUE_LIGHT = TextColor.color(0x7070FF);
    public static final TextColor BLUE_LIGHT_2 = TextColor.color(0xAAAAFF);
    public static final TextColor BLUE_LIGHT_3 = TextColor.color(0xD4D4FF);
    public static final TextColor PURPLE_DARK_3 = TextColor.color(0x2A007F);
    public static final TextColor PURPLE_DARK_2 = TextColor.color(0x5500AA);
    public static final TextColor PURPLE_DARK = TextColor.color(0x7F2AD4);
    public static final TextColor PURPLE = TextColor.color(0xAA55FF);
    public static final TextColor PURPLE_LIGHT = TextColor.color(0xAA7FFF);
    public static final TextColor PURPLE_LIGHT_2 = TextColor.color(0xD4AAFF);
    public static final TextColor MAGENTA_DARK_3 = TextColor.color(0x550055);
    public static final TextColor MAGENTA_DARK_2 = TextColor.color(0x7F007F);
    public static final TextColor MAGENTA_DARK = TextColor.color(0xAA00AA);
    public static final TextColor MAGENTA = TextColor.color(0xD42AD4);
    public static final TextColor MAGENTA_LIGHT = TextColor.color(0xFF55FF);
    public static final TextColor MAGENTA_LIGHT_2 = TextColor.color(0xFFAAFF);
    public static final TextColor MAGENTA_LIGHT_3 = TextColor.color(0xFFD4FF);
    public static final TextColor PINK_DARK_2 = TextColor.color(0xD5007F);
    public static final TextColor PINK_DARK = TextColor.color(0xFF00AA);
    public static final TextColor PINK = TextColor.color(0xFF55AA);
    public static final TextColor PINK_LIGHT = TextColor.color(0xFF7FD4);
    public static final TextColor ROSE_DARK_2 = TextColor.color(0xFF0055);
    public static final TextColor ROSE_DARK = TextColor.color(0xFF557F);
    public static final TextColor ROSE = TextColor.color(0xFF7FAA);
    public static final TextColor ROSE_LIGHT = TextColor.color(0xFFAAD4);
    public static final TextColor BROWN_DARK_2 = TextColor.color(0x552A00);
    public static final TextColor BROWN_DARK = TextColor.color(0x80552A);
    public static final TextColor BROWN = TextColor.color(0xAA8055);
    public static final TextColor BROWN_LIGHT = TextColor.color(0xD4AA80);
    public static final TextColor BROWN_LIGHT_2 = TextColor.color(0xFFD4AA);
    public static final TextColor BLACK = TextColor.color(0x000000);
    public static final TextColor GRAY_DARK_2 = TextColor.color(0x2A2A2A);
    public static final TextColor GRAY_DARK = TextColor.color(0x555555);
    public static final TextColor GRAY = TextColor.color(0x808080);
    public static final TextColor GRAY_LIGHT = TextColor.color(0xAAAAAA);
    public static final TextColor GRAY_LIGHT_2 = TextColor.color(0xD4D4D4);
    public static final TextColor WHITE = TextColor.color(0xFFFFFF);
    public static final TextColor GREEN_DESATURATED_TEMP = TextColor.color(0xAAD4AA);
    public static final TextColor AQUA_DESATURATED = TextColor.color(0x55AAAA);
    public static final TextColor SKY_DESATURATED = TextColor.color(0x557FD4);
}
